repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: crossplane-stable
    url: https://charts.crossplane.io/stable

releases:
  - name: my-grafana
    namespace: monitoring
    chart: grafana/grafana
    values:
      - grafana-values.yaml
    version: 8.8.4
  - name: crossplane
    namespace: crossplane-system
    chart: crossplane-stable/crossplane
    createNamespace: true
