apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: keycloak-demo
resources:
- provider-keycloak-admin.yaml
- keycloak-client-config.yaml
