apiVersion: v1
kind: Secret
metadata:
  name: keycloak-sdlc-admin-credentials
  namespace: crossplane-system
  labels:
    type: provider-credentials
type: Opaque
stringData:
  client_id: "temp admin"
  username: "federiconafria"
  password: "69b28df306754cb5901cc296de96bb82"
  url: "http://example-kc-service.default.svc.cluster.local:8080"
  base_path: "/auth"
  realm: "SDLCBox"
---
apiVersion: keycloak.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: sdlcbox
spec:
  credentials:
    source: Secret
    secretRef:
      name: keycloak-credentials
      namespace: crossplane-system
      key: credentials
